# Generated by Django 3.2.13 on 2022-11-17 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=200)),
                ('movie_id', models.IntegerField()),
                ('original_title', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('overview', models.TextField(max_length=50)),
                ('release_date', models.CharField(max_length=50)),
                ('vote_average', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=50)),
                ('backdrop_path', models.CharField(max_length=50)),
                ('runtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VoteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('like_moveis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('like_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
