# Generated by Django 3.2.13 on 2022-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behinds', '0002_auto_20221117_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='behind',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
