# Generated by Django 3.2.13 on 2022-11-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behinds', '0003_behind_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='behind_at',
            new_name='behind',
        ),
    ]
