# Generated by Django 3.2.13 on 2022-11-18 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('behinds', '0004_rename_behind_at_comment_behind'),
    ]

    operations = [
        migrations.AddField(
            model_name='behind',
            name='like_user',
            field=models.ManyToManyField(related_name='like_behinds', to=settings.AUTH_USER_MODEL),
        ),
    ]
